apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lbaas.openstack.org
spec:
  group: openstack.org
  version: v1
  scope: Namespaced
  names:
    plural: lbaas
    singular: lbaa
    kind: LBaa 
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            ip:
              type: string
            lb_ip:
              type: null
            ports: 
              type: array
            project_id:
              type: string
            security_groups_ids:
              type: string
            subnet_id:
              type: string
            type:
              type: string
